### ISSUE TITLE
Supporting thread pooling

### ISSUE THREAD

**Issue by jballant** [pwagener/backbone.conduit#59]
If you create multiple SparseCollections, a Worker thread is initialized for each collection (if I'm not mistaken). This might not always be ideal. Having lots of workers could be taxing on the client machine.

Support for thread pooling would fix this problem. Something like what you would see in http://threadsjs.readthedocs.io/en/latest/.

Currently, you can supply your own Worker constructor through the Conduit config, but since each Worker thread global has the complete raw data set, it looks like there is not a practical way to share threads without stomping on the raw data each thread might haul for their respective collections. Mapping this raw data to an id number for the collection and then passing it as part of the messages to workers might fix this problem. With that, it might be possible to have workers that can have multiple "contexts" for the collections that they manage data for.

It would also potentially open up the possibility of adding support for intelligent caching the raw data for multiple collections as well. That way you could have multiple sparse collections with different projections on the same source raw data.

**Comment by pwagener** [comment]
Fixed in v1.1.  Thanks @jballant !
